### ISSUE TITLE
pagination를 Infinite list로

### ISSUE THREAD

**Issue by jngbng** [hackerstalk/hackerstalk#6]
다음 페이지 링크를 누르면 react의 특성 때문에 화면은 바뀌는데
스크롤은 잴 위로 안 올라감.
차라리 끝에가면 추가 로딩을 하는 Infinite list로 바꾸는건 어떨까.

**Comment by bbirec** [comment]
개인적으로 infinite scroll은 더 불편하다고 생각함.
Scroll top을 해주는게 더 나을듯
